# Generated by Django 4.2.11 on 2024-07-09 14:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('registration_period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=220, null=True)),
                ('venue', models.CharField(blank=True, max_length=220, null=True)),
                ('private', models.BooleanField(blank=True, default=False, null=True)),
                ('city', models.CharField(blank=True, max_length=220, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('has_live_matches', models.BooleanField(blank=True, default=False, null=True)),
                ('tier', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tournament_url', models.TextField(blank=True, null=True)),
                ('free_to_spectate', models.BooleanField(blank=True, default=False, null=True)),
                ('is_followed', models.BooleanField(blank=True, default=False, null=True)),
                ('last_match_date', models.PositiveBigIntegerField(blank=True, null=True)),
                ('pro_circuit_points', models.CharField(blank=True, max_length=220, null=True)),
                ('banner', models.CharField(blank=True, max_length=220, null=True)),
                ('stop_sales_time', models.CharField(blank=True, max_length=15, null=True)),
                ('image_uri', models.TextField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=220, null=True)),
                ('end_datetime', models.PositiveBigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=220, null=True)),
                ('prize_pool', models.CharField(blank=True, max_length=220, null=True)),
                ('base_prize_pool', models.CharField(blank=True, max_length=220, null=True)),
                ('region', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_datetime', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_over', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'leagues',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('type', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team_one_win_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team_two_win_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('winning_team_id', models.PositiveIntegerField(blank=True, null=True)),
                ('last_match_date_time', models.PositiveBigIntegerField(blank=True, null=True)),
                ('losing_team_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_over', models.BooleanField(blank=True, default=False, null=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='leagues.league', to_field='id')),
                ('team_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_one_series', to='teams.team', to_field='id')),
                ('team_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_two_series', to='teams.team', to_field='id')),
            ],
            options={
                'db_table': 'series',
                'ordering': ['-last_match_date_time'],
            },
        ),
    ]
