# Generated by Django 4.2.11 on 2024-07-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
        ('players', '0002_player_pick_bans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='pick_bans',
        ),
        migrations.AddField(
            model_name='player',
            name='pick_bans',
            field=models.ManyToManyField(blank=True, related_name='player', to='stats.popularmatchpickban'),
        ),
    ]
