# Generated by Django 4.2.11 on 2024-07-09 14:51

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(blank=True, max_length=10, null=True)),
                ('date_created', models.CharField(blank=True, max_length=20, null=True)),
                ('is_pro', models.BooleanField(default=False, null=True)),
                ('is_locked', models.BooleanField(default=False, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('base_logo', models.URLField(blank=True, null=True)),
                ('banner_logo', models.URLField(blank=True, null=True)),
                ('sponsor_logo', models.URLField(blank=True, null=True)),
                ('win_count', models.IntegerField(blank=True, null=True)),
                ('loss_count', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('last_match_date_time', models.BigIntegerField(blank=True, null=True)),
                ('coach_steam_account_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_followed', models.BooleanField(default=False, null=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['-rank'],
            },
        ),
    ]
