# Generated by Django 4.2.11 on 2024-07-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
        ('teams', '0002_team_pick_bans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='pick_bans',
        ),
        migrations.AddField(
            model_name='team',
            name='pick_bans',
            field=models.ManyToManyField(blank=True, related_name='team', to='stats.popularmatchpickban'),
        ),
    ]
