# Generated by Django 4.2.11 on 2024-07-09 13:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slot', models.IntegerField(blank=True, null=True)),
                ('ability_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hero_id', models.IntegerField(blank=True, null=True)),
                ('game_version_id', models.IntegerField(blank=True, null=True)),
                ('language_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('hype', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('game_version_id', models.IntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField(blank=True, null=True)),
                ('hero_unlock_order', models.IntegerField(blank=True, null=True)),
                ('team', models.BooleanField(blank=True, null=True)),
                ('cm_enabled', models.BooleanField(blank=True, null=True)),
                ('new_player_enabled', models.BooleanField(blank=True, null=True)),
                ('attack_type', models.CharField(blank=True, max_length=255, null=True)),
                ('starting_armor', models.FloatField(blank=True, null=True)),
                ('starting_magic_armor', models.FloatField(blank=True, null=True)),
                ('starting_damage_min', models.FloatField(blank=True, null=True)),
                ('starting_damage_max', models.FloatField(blank=True, null=True)),
                ('attack_rate', models.FloatField(blank=True, null=True)),
                ('attack_animation_point', models.FloatField(blank=True, null=True)),
                ('attack_acquisition_range', models.FloatField(blank=True, null=True)),
                ('attack_range', models.FloatField(blank=True, null=True)),
                ('attribute_primary', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_primary_attribute', models.IntegerField(blank=True, null=True)),
                ('strength_base', models.FloatField(blank=True, null=True)),
                ('strength_gain', models.FloatField(blank=True, null=True)),
                ('intelligence_base', models.FloatField(blank=True, null=True)),
                ('intelligence_gain', models.FloatField(blank=True, null=True)),
                ('agility_base', models.FloatField(blank=True, null=True)),
                ('agility_gain', models.FloatField(blank=True, null=True)),
                ('hp_regen', models.FloatField(blank=True, null=True)),
                ('mp_regen', models.FloatField(blank=True, null=True)),
                ('move_speed', models.FloatField(blank=True, null=True)),
                ('move_turn_rate', models.FloatField(blank=True, null=True)),
                ('hp_bar_offset', models.FloatField(blank=True, null=True)),
                ('vision_daytime_range', models.FloatField(blank=True, null=True)),
                ('vision_nighttime_range', models.FloatField(blank=True, null=True)),
                ('complexity', models.IntegerField(blank=True, null=True)),
                ('primary_attribute_enum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slot', models.IntegerField(blank=True, null=True)),
                ('game_version_id', models.IntegerField(blank=True, null=True)),
                ('ability_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.PositiveSmallIntegerField(editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('aliases', models.JSONField(blank=True, null=True)),
                ('abilities', models.ManyToManyField(blank=True, to='heroes.ability')),
                ('language', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='heroes.language', to_field='language_id')),
                ('roles', models.ManyToManyField(blank=True, to='heroes.role')),
                ('stat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='heroes.stat')),
                ('talents', models.ManyToManyField(blank=True, to='heroes.talent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
